sudo: required

language: bash

env:
  - VERSION=4.6 VARIANT=

services:
  - docker

install:
  - docker pull buildpack-deps:curl

before_script:
  - image="adminer:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - docker build -t $image ${VERSION}${VARIANT:+/$VARIANT}
  - docker run --name adminer -d $image
  - "docker run -i --rm --link adminer:adminer buildpack-deps:curl curl -fsSL http://adminer:8080 |grep '<span class=\"version\">'${VERSION}"
  - docker restart adminer
  - "docker run -i --rm --link adminer:adminer buildpack-deps:curl curl -fsSL http://adminer:8080 |grep '<span class=\"version\">'${VERSION}"
  - docker run --name adminer_design -e ADMINER_DESIGN=nette -d $image
  - "docker run -i --rm --link adminer_design:adminer buildpack-deps:curl curl -fsSL http://adminer:8080 |grep 'adminer.css'"
  - "docker run -i --rm --link adminer_design:adminer buildpack-deps:curl curl -fsSL http://adminer:8080/adminer.css |grep 'Nette'"
  - docker run --name adminer_server -e ADMINER_DEFAULT_SERVER=ADMINER_DEFAULT_SERVER_WORKS -d $image
  - "docker run -i --rm --link adminer_server:adminer buildpack-deps:curl curl -fsSL http://adminer:8080 |grep 'ADMINER_DEFAULT_SERVER_WORKS'"

after_script:
  - docker ps -a
  - docker images
